// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.icraft.iras.model;

import java.lang.String;

privileged aspect Lvl_Roo_JavaBean {
    
    public String Lvl.getName() {
        return this.name;
    }
    
    public void Lvl.setName(String name) {
        this.name = name;
    }
    
}
