// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.icraft.iras.model;

import com.icraft.iras.model.JobTitle;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect JobTitleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: JobTitleDataOnDemand: @Component;
    
    private Random JobTitleDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<JobTitle> JobTitleDataOnDemand.data;
    
    public JobTitle JobTitleDataOnDemand.getNewTransientJobTitle(int index) {
        com.icraft.iras.model.JobTitle obj = new com.icraft.iras.model.JobTitle();
        obj.setAverageRate(new Integer(index).doubleValue());
        obj.setTitle("title_" + index);
        return obj;
    }
    
    public JobTitle JobTitleDataOnDemand.getSpecificJobTitle(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        JobTitle obj = data.get(index);
        return JobTitle.findJobTitle(obj.getId());
    }
    
    public JobTitle JobTitleDataOnDemand.getRandomJobTitle() {
        init();
        JobTitle obj = data.get(rnd.nextInt(data.size()));
        return JobTitle.findJobTitle(obj.getId());
    }
    
    public boolean JobTitleDataOnDemand.modifyJobTitle(JobTitle obj) {
        return false;
    }
    
    public void JobTitleDataOnDemand.init() {
        data = com.icraft.iras.model.JobTitle.findJobTitleEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'JobTitle' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.icraft.iras.model.JobTitle>();
        for (int i = 0; i < 10; i++) {
            com.icraft.iras.model.JobTitle obj = getNewTransientJobTitle(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
